# Site settings
title: "Hacken01"
description: "Personal website of Hacken01"
url: "https://hacken01.github.io"
author: Hacken01
email: arancibiagabriel@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Custom settings
show_downloads: false
google_analytics: # Add your tracking ID if needed

# Navigation
navigation:
  - name: Home
    url: /
  - name: About
    url: /about
  - name: Portfolio
    url: /portfolio
  - name: Contact
    url: /contact
